import React from "react";
import { useTranslation } from "react-i18next";
import { ItemEditorEmptyView } from "../../components/ItemEditor";
import "./ComplianceAssessmentItem.scss";

interface ComplianceAssessmentItemEmptyViewProps {
  /** Set when the item has no smAssessmentId yet, or when the SM API fetch failed. */
  reason: "not-linked" | "fetch-failed";
  detail?: string;
}

/**
 * Shown when this Fabric item is not (yet) bound to a Sound Management
 * compliance assessment, or the fetch to SM's API failed. Assessments are
 * generated by SM's own compliance engine, never authored by a user in the
 * Fabric portal, so there is no "create/getting started" flow here - only
 * these two failure states.
 */
export function ComplianceAssessmentItemEmptyView({ reason, detail }: ComplianceAssessmentItemEmptyViewProps) {
  const { t } = useTranslation();

  const title = reason === "not-linked"
    ? t('ComplianceAssessmentItemEmptyView_NotLinked_Title', 'Not yet linked to Sound Management')
    : t('ComplianceAssessmentItemEmptyView_FetchFailed_Title', 'Could not load assessment data');

  const description = reason === "not-linked"
    ? t('ComplianceAssessmentItemEmptyView_NotLinked_Description', 'This item has no bound compliance assessment. Sound Management creates and binds these items automatically when it generates a new assessment.')
    : (detail ?? t('ComplianceAssessmentItemEmptyView_FetchFailed_Description', 'The request to Sound Management\'s API did not succeed.'));

  return (
    <ItemEditorEmptyView
      title={title}
      description={description}
      imageSrc="/assets/items/ComplianceAssessmentItem/EditorEmpty.svg"
      imageAlt="Empty state illustration"
      tasks={[]}
    />
  );
}
